language: python
python: "3.7"
dist: bionic

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

services:
  - docker

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=yes
    - DOCKER_IMAGE_NAME=iomirea/run-api-public

install:
  - pip install --upgrade pip
  # - pip3 install -r requirements.txt
  - pip install pre-commit

script:
  - pre-commit run --all-files

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull "$DOCKER_IMAGE_NAME" || true
  - docker build --cache-from "$DOCKER_IMAGE_NAME" -t "$DOCKER_IMAGE_NAME" .
  - docker push "$DOCKER_IMAGE_NAME"
