dist: bionic
language: python
python: "3.7"

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

services:
  - docker

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=yes
    - DOCKER_IMAGE_NAME=iomirea/run-api-public

before_install:
  - docker pull "$DOCKER_IMAGE_NAME" || true  # pull to use image as cache
  - docker build --cache-from "$DOCKER_IMAGE_NAME" -t "$DOCKER_IMAGE_NAME" .

install:
  - pip install --upgrade pip
  # - pip3 install -r requirements.txt
  - pip install pre-commit

script:
  - pre-commit run --all-files

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: master
