version: ~> 1.0

os: linux
dist: bionic
language: python
python: 3.7

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

services:
  - docker

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=yes
    - DOCKER_IMAGE_NAME=iomirea/run-api-public

before_install:
  - docker pull "$DOCKER_IMAGE_NAME" || true  # pull to use image as cache
  - docker build --cache-from "$DOCKER_IMAGE_NAME" -t "$DOCKER_IMAGE_NAME" .

install:
  - pip install pre-commit  # -r requirements.txt

script:
  - pre-commit run --all-files

deploy:
  edge: true
  cleanup: false
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: master
